--DROP TABLE departamentos;
CREATE TABLE departamentos (codDepto VARCHAR(4) NOT NULL PRIMARY KEY,
	nombreDpto VARCHAR(20) NOT NULL,
	ciudad VARCHAR(15),
	codDirector VARCHAR(12)
);
	
--DROP TABLE empleados;
CREATE TABLE empleados (
  nDIEmp VARCHAR(12) NOT NULL PRIMARY KEY,
  nomEmp VARCHAR(30) NOT NULL,
  sexEmp CHAR(1) NOT NULL,
  fecNac DATE NOT NULL,
  fecIncorporacion DATE NOT NULL,
  salEmp FLOAT NOT NULL,
  comisionE FLOAT NOT NULL,
  cargoE VARCHAR(15) NOT NULL,
  jefeID VARCHAR(12),
  codDepto varchar(4) NOT NULL
);


--ALTER TABLE departamentos ADD CONSTRAINT FK_DIR FOREIGN KEY (codDirector) REFERENCES empleados (nDIEmp) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE empleados ADD CONSTRAINT FK_DPTO FOREIGN KEY (codDepto) REFERENCES departamentos (codDepto) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE empleados ADD CONSTRAINT FK_JEFE_EMP FOREIGN KEY (jefeID) REFERENCES empleados (nDIEmp) ON DELETE NO ACTION ON UPDATE NO ACTION;
